### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by andypost** [fgm/rabbitmq#1]
To properly describe dependencies

**Comment by fgm** [comment]
Globally in favor of that, but since 8.0.x doesn't yet have an official composer install process, could you update the README with a pointer to a page about composer use in modules like this, e.g. composer_manager, or the drupal_project composer skeleton, or whatever ?

**Comment by fgm** [comment]
This was fixed in 405ab2d287c5cd9068b3d75afa2a94aa921821af 2016-03-17.
